"""
hexiga.demo.demo_hooks
======================

A hooks geometry
built from a set of linear hexahedral patches (degree-elevated to cubic via
``nrbdelev(..., [2,2,2])``).  The four base corner-matrix pairs ``H1_0..H4_0``
/ ``H*_1`` are identical to ``demoSocketCAD``; the remaining patches are
generated by mirror/rotation transforms, then a subset is selected via the
literal MATLAB index expression ``idxs = [1:7, 9:length(mpHexa)-1]``.

Signature: ``mpHooks = demoHooksCAD(varargin)`` with options
``'RIN'``, ``'ROUT'``, ``'SMOOTH'``, ``'TURBOSMOOTH'``, ``'VISUALISE'``,
``'BENCHMARK'``, ``'PUBLISH'`` (defaults ``rin=2.5, rout=4, smooth=True,
turbosmooth=False, benchmark=True, visualise=False, publish=False``).

Notes
-----

* ``genHooks`` is ported verbatim: 4 base corner-matrix pairs become hexes
  via the idiom ``nrbdelev( nrbmak( cat(4, c0, c1), {k1, k2, [0 0 1 1]}) ,
  [2 2 2] )``; ``H5 = mirrorX(H4)``, ``H6 = mirrorX(H3)``;
  ``H7 = mirrorYoff(H6)``, ``H8 = mirrorYoff(H5)`` (``mirrorYoff`` carries a
  ``-2*rout`` x-translation); ``H9..H16 = rot90X(mirrorY(H1..H8))``.
* The selected subset uses the literal MATLAB expression
  ``idxs = [1:7, 9:length(mpHexa)-1]`` (1-based).
* **MATLAB BUG (reproduced literally):** the ``'RIN'`` option writes to the
  unused ``OPTs.replicates`` field and the ``'ROUT'`` option to the unused
  ``OPTs.zLevels`` field, so overriding ``rin``/``rout`` has no effect.  The
  typo message name is ``"demoAsymSocketCAD"`` (a copy/paste artifact of the
  original, preserved verbatim).
* The ``smooth`` path calls ``mpTurboSmooth`` -- not yet ported (A4) -- and
  is preserved literally, raising :class:`NotImplementedError`.
* ``visualise``/``benchmark`` are MATLAB-side conveniences with no solver
  effect; accepted and ignored (consistent with the A2 synthetic demo ports).
"""

from __future__ import annotations

from typing import List, Sequence

import numpy as np

from ..nurbs.nrb import Nrb
from ..nurbs.degelev import nrbdegelev
from ..nurbs.make import nrbmak
from ..nurbs.tform import nrbtform
from ..nurbs.surf4 import nrb4surf
from ..smth.mp_turbo_smooth import mp_turbo_smooth
from ..smth.mp_turbo_smooth import mp_turbo_smooth
from .demo_socket import _mk_hexa

__all__ = ["demoHooksCAD", "genHooks"]

def _get_inputs(inputs: Sequence):
    class OPTs:
        rin: float = 2.5
        rout: float = 4
        visualise: bool = False
        smooth: bool = True
        turbosmooth: bool = False
        benchmark: bool = True
        publish: bool = False

    opts = OPTs()
    n = len(inputs)
    jj = 0
    while jj < n:
        key = str(inputs[jj]).upper()
        if jj + 1 < n:
            val = inputs[jj + 1]
            s = str(val)
            flag = (s[0].lower() in ("t", "true")) if s else False
        else:
            flag = False
        if key == "RIN":
            # MATLAB BUG (literal): writes to the unused `replicates` field.
            opts.replicates = val[0] if hasattr(val, "__len__") else val
        elif key == "ROUT":
            # MATLAB BUG (literal): writes to the unused `zLevels` field.
            opts.zLevels = val[0] if hasattr(val, "__len__") else val
        elif key == "SMOOTH":
            opts.smooth = flag
        elif key == "TURBOSMOOTH":
            opts.turbosmooth = flag
        elif key == "VISUALISE":
            opts.visualise = flag
        elif key == "BENCHMARK":
            opts.benchmark = flag
        elif key == "PUBLISH":
            opts.publish = flag
        else:
            value = inputs[jj + 1] if jj + 1 < n else ""
            print(f" * demoAsymSocketCAD: Unrecognised Parsed Parameter: {value} - Default Applied.")
        jj += 2
    if opts.publish:
        opts.visualise = True
        opts.smooth = True
        opts.turbosmooth = True
    return opts

def genHooks(rin: float, rout: float) -> List[Nrb]:
    """Port of ``genHooks(rin, rout)``: 16 cubic hooks patches."""
    hgt = rout

    # Base corner matrices -- identical to demoSocketCAD (H1..H4).
    H1_0 = np.array(
        [
            [rin - rout, 0, rin * np.sqrt(2) / 2 - rout, 0],
            [0, 0, rin * np.sqrt(2) / 2, rout],
            [0, 0, 0, 0],
        ]
    )
    H1_1 = H1_0.copy()
    H1_1[2, :] = hgt

    H2_0 = np.array(
        [
            [rin * np.sqrt(2) / 2 - rout, 0, -rout, -rout],
            [rin * np.sqrt(2) / 2, rout, rin, rout],
            [0, 0, 0, 0],
        ]
    )
    H2_1 = H2_0.copy()
    H2_1[2, :] = hgt

    H3_0 = np.array(
        [
            [-rout, -rout, -rin * np.sqrt(2) / 2 - rout, -rout * np.sqrt(2) / 2 - rout],
            [rin, rout, rin * np.sqrt(2) / 2, rout * np.sqrt(2) / 2],
            [0, 0, 0, 0],
        ]
    )
    H3_1 = H3_0.copy()
    H3_1[2, :] = hgt

    H4_0 = np.array(
        [
            [-rin * np.sqrt(2) / 2 - rout, -rout * np.sqrt(2) / 2 - rout, -rin - rout, -2 * rout],
            [rin * np.sqrt(2) / 2, rout * np.sqrt(2) / 2, 0, 0],
            [0, 0, 0, 0],
        ]
    )
    H4_1 = H4_0.copy()
    H4_1[2, :] = hgt

    H1_nrb = _mk_hexa(H1_0, H1_1)
    H2_nrb = _mk_hexa(H2_0, H2_1)
    H3_nrb = _mk_hexa(H3_0, H3_1)
    H4_nrb = _mk_hexa(H4_0, H4_1)

    Tform_mirrorX = np.array(
        [[1, 0, 0, 0], [0, -1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]
    )
    Tform_mirrorYoff = np.array(
        [[-1, 0, 0, -2 * rout], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]
    )

    H5_nrb = nrbtform(H4_nrb, Tform_mirrorX)
    H6_nrb = nrbtform(H3_nrb, Tform_mirrorX)

    H7_nrb = nrbtform(H6_nrb, Tform_mirrorYoff)
    H8_nrb = nrbtform(H5_nrb, Tform_mirrorYoff)

    Tform_mirrorY = np.array(
        [[-1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]]
    )
    Tform_rot90X = np.array(
        [[1, 0, 0, 0], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 1]]
    )

    H9_nrb = nrbtform(nrbtform(H1_nrb, Tform_mirrorY), Tform_rot90X)
    H10_nrb = nrbtform(nrbtform(H2_nrb, Tform_mirrorY), Tform_rot90X)
    H11_nrb = nrbtform(nrbtform(H3_nrb, Tform_mirrorY), Tform_rot90X)
    H12_nrb = nrbtform(nrbtform(H4_nrb, Tform_mirrorY), Tform_rot90X)
    H13_nrb = nrbtform(nrbtform(H5_nrb, Tform_mirrorY), Tform_rot90X)
    H14_nrb = nrbtform(nrbtform(H6_nrb, Tform_mirrorY), Tform_rot90X)
    H15_nrb = nrbtform(nrbtform(H7_nrb, Tform_mirrorY), Tform_rot90X)
    H16_nrb = nrbtform(nrbtform(H8_nrb, Tform_mirrorY), Tform_rot90X)

    return [
        H1_nrb, H2_nrb, H3_nrb, H4_nrb, H5_nrb, H6_nrb, H7_nrb, H8_nrb,
        H9_nrb, H10_nrb, H11_nrb, H12_nrb, H13_nrb, H14_nrb, H15_nrb, H16_nrb,
    ]

def demoHooksCAD(*inputs) -> List[Nrb]:
    """Port of ``demoHooksCAD(varargin)``: selected cubic hooks patches.

    The selected subset mirrors the literal MATLAB expression
    ``idxs = [1:7, 9:length(mpHexa)-1]`` (1-based).  The ``smooth`` path is
    preserved literally and raises :class:`NotImplementedError` until
    ``mpTurboSmooth`` (A4) is ported.
    """
    OPTs = _get_inputs(inputs)

    mpHexa = genHooks(OPTs.rin, OPTs.rout)
    # Literal MATLAB: idxs = [1:7, 9:length(mpHexa)-1]  (1-based).
    idxs = list(range(1, 8)) + list(range(9, len(mpHexa)))
    mpHooks = [mpHexa[i - 1] for i in idxs]

    if OPTs.smooth:
        if OPTs.turbosmooth:
            mpHooks = mp_turbo_smooth(mpHooks, "TURBO", True, "TURBOCYCLES", 4)
        else:
            mpHooks = mp_turbo_smooth(mpHooks)

    return mpHooks
